### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by slulego**

### CODE REVIEW

**Comment by slulego** [comment]
I won't be offended if you don't want to use it. I was trying to make it look like it belongs to unibeautify.com and vscode. A good icon can boost the popularity quite a bit sometimes.

**Comment by muuvmuuv** [comment]
Good start! But I would not give it a shadow. We are not using hard shadows in the rest of the design and I don‘t think it fits into the design system. 
Is the background color the same as the header color from the website? 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by slulego** [comment]
@muuvmuuv Yea the background is the same dark blue color.
Did you have something else in mind for an icon? I was thinking about just the blue logo with a white outline, or a white logo with a blue outline. I felt it looked a little small because it's a little tall but it might work.

**Comment by szeck87** [comment]
Does this belong in the VSCode repo?

**Comment by muuvmuuv** [comment]
For the moment. @Glavin001 will update all icons and logos in time. When we accept a final version I will add it to our CI sketch file and export it to any sizes we need for all platforms

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Glavin001** [comment]
@muuvmuuv should we close this issue for now then?

Regardless, thank you @slulego for your interest in Unibeautify and your contribution. Please let us know if there's anything else you'd like to contribute 😃 .

**Pull request closed without merging**
