### PR TITLE
First working version!

### PR DESCRIPTION
**Pull request by Glavin001**
mar-09-2018 22-55-41

### CODE REVIEW

**Comment by mblode** [comment]
How can I help with this project's development?

**Comment by szeck87** [comment]
Why Mocha instead of Jest?

**Comment by Glavin001** [comment]
@mblode : Awesome to hear! I am still setting up the foundation. I will try to create more Issues soon with label `good first issue` and/or `help wanted` which would be great places for you to start contributing 😃.

**Comment by Glavin001** [comment]
@szeck87 : I plan on switching them over to Jest. I used https://github.com/Microsoft/vscode-generator-code/tree/20af6eee7d7b22f2236f6c2d1a7b7809a519392e/generators/app/templates/ext-command-ts to get started. Could not find a Jest example. Will be coming in a future PR, or maybe something another contributor could work on 😉. I created https://github.com/Unibeautify/vscode/issues/8 for anyone to take.

**Comment by Glavin001** [comment]
I'm having major troubles publishing the extension. See https://github.com/Unibeautify/vscode/issues/11#issuecomment-372008893 . Please help if you can!

**Pull request merged**
