### PR TITLE
Add PHP_CodeSniffer beautifier

### PR DESCRIPTION
**Pull request by Glavin001**
Beautifier: https://github.com/Unibeautify/beautifier-php-codesniffer
Related: https://github.com/Unibeautify/website/pull/102

### CODE REVIEW

**Comment by Glavin001** [comment]
Published to v0.5.0

**Comment by Glavin001** [comment]
@muuvmuuv please give it a try and let us know if it works for you 😃 .

**Comment by muuvmuuv** [comment]
@Glavin001 damn, awesome! It works so fine! 😍 Now my code is perfectly aligned and intended, nice! Is it automatically using my .php_cs or the conf from Unibeautify?

**Comment by Glavin001** [comment]
Glad to hear it is working for you!

> Is it automatically using my .php_cs or the conf from Unibeautify?

@muuvmuuv depends if you're using `prefer_beautifier_config`: https://unibeautify.com/docs/beautifier-php_codesniffer.html#advanced
I did add support to detect `.php_cs` if you have `prefer_beautifier_config` enabled 😃 .

**Pull request merged**
