### PR TITLE
Migrate from Mocha to Jest

### PR DESCRIPTION
**Pull request by szeck87**
Used a lot of code from https://github.com/strothj/vscode-gist-manager/tree/master/src/test to use a Jest based test runner.  One thing that had to be done, unless there is another way that I don't know how to do, is the addition of `"esModuleInterop": true` to tsconfig.json.  It didn't seem to recognize a tsconfig.json file or that option inside of the test folder, so it had to be put in the root.  This was because https://github.com/szeck87/vscode/blob/migrate-to-jest/test/jest-vscode-environment.ts#L11 kept throwing a `typeerror: class extends value undefined is not a constructor or null` error, which indicates a circular reference issue (I think).

### CODE REVIEW

**Comment by szeck87** [comment]
Hey @Glavin001 did you ever give this a try?

**Comment by Glavin001** [comment]
Tests work. Seems like I cannot debug though.

**Comment by szeck87** [comment]
Where are you putting a breakpoint and which test run?

**Comment by Glavin001** [comment]
I put breakpoint in `test/extension.test.ts`and ran `Launch Tests`.

**Comment by szeck87** [comment]
Hmm, ok.  Try putting a breakpoint at index.ts line 7 (first line of `activate`).  It should stop there.

**Pull request merged**
